version: '3'
services:
  db:
    image: postgres:latest
    ports:
      - 9432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    user: root
  web:
    image: php:7.4-apache
    volumes:
      - "./index.php:/var/www/html/index.php"
      - "./application:/var/www/html/application"
      - "./system:/var/www/html/system"
      - "./vendor:/var/www/html/vendor"
    ports:
      - 80:80

